# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import languages.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=languages.models.download_media_location),
        ),
    ]
