# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160312_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.download_media_location),
        ),
    ]
