# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 31, 21, 56, 42, 742754, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
