# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160419_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visualized',
            field=models.BooleanField(default=False),
        ),
    ]
