# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_message_visualized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 25, 19, 5, 50, 907462, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
